# Generated by Django 4.2.11 on 2024-04-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
